# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Start ssPanl CheckIn

on:
 watch:
    types: started
 schedule:
  # 定时任务，在每天的8点进行机场签到
  - cron: '0 0 * * *'

jobs:
  checkIn:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps: 
    - name: 'Checkout codes'
      uses: actions/checkout@v1
    - name: python install package
      run: python -m pip install --upgrade pip && if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: checkIn Yingyun
      run: python3 CheckIn.py -e ${{secrets.USERNAME}} -p ${{secrets.PASSWORD}} -s "https://yingyun-g.pw"
